import { db } from '@/db';
import { learningCertificates, learningPaths, userLearningProgress } from '@/db/schema';
import { eq, and, desc } from 'drizzle-orm';
import type { NewLearningCertificate, CertificateIssuanceCriteria } from '@/types/learning-paths';

/**
 * Issue a certificate to a user for completing a learning path
 */
export async function issueCertificate(
  userId: string,
  pathId: string,
  certificateNumber: string,
  actorId?: string
): Promise<NewLearningCertificate | null> {
  // Check if certificate already exists
  const existing = await db
    .select()
    .from(learningCertificates)
    .where(
      and(
        eq(learningCertificates.userId, userId),
        eq(learningCertificates.pathId, pathId)
      )
    )
    .limit(1);

  if (existing.length > 0) {
    return null; // Certificate already issued
  }

  // Validate eligibility
  const isEligible = await validateCertificateEligibility(userId, pathId);
  if (!isEligible) {
    throw new Error('User is not eligible for certificate');
  }

  // Generate certificate URL (placeholder - would be generated by generation module)
  const certificateUrl = `/certificates/${certificateNumber}`;

  // Issue certificate
  const results = await db
    .insert(learningCertificates)
    .values({
      userId,
      pathId,
      certificateNumber,
      certificateUrl,
      status: 'issued',
    })
    .returning();

  return results[0] || null;
}

/**
 * Validate if a user is eligible for a certificate
 */
export async function validateCertificateEligibility(
  userId: string,
  pathId: string
): Promise<boolean> {
  const criteria: CertificateIssuanceCriteria = {
    pathId,
    requiredCompletionPercentage: 100,
    requiredAssessmentScore: 70,
    minimumTimeSpent: 0, // No minimum time requirement
  };

  // Check completion percentage
  const progressMetrics = await getPathCompletionMetrics(userId, pathId);
  if (progressMetrics.overallProgress < criteria.requiredCompletionPercentage) {
    return false;
  }

  // Check assessment scores (placeholder - would integrate with assessment system)
  // const assessmentScore = await getAverageAssessmentScore(userId, pathId);
  // if (assessmentScore < criteria.requiredAssessmentScore) {
  //   return false;
  // }

  // Check minimum time spent
  if (progressMetrics.totalTimeSpent < criteria.minimumTimeSpent) {
    return false;
  }

  return true;
}

/**
 * Get path completion metrics for certificate eligibility
 */
async function getPathCompletionMetrics(
  userId: string,
  pathId: string
): Promise<{ overallProgress: number; totalTimeSpent: number }> {
  const progressRecords = await db
    .select()
    .from(userLearningProgress)
    .where(
      and(
        eq(userLearningProgress.userId, userId),
        eq(userLearningProgress.pathId, pathId)
      )
    );

  const totalProgress = progressRecords.reduce((sum, p) => sum + (p.progressPercentage || 0), 0);
  const overallProgress = progressRecords.length > 0 ? totalProgress / progressRecords.length : 0;
  const totalTimeSpent = progressRecords.reduce((sum, p) => sum + (p.timeSpent || 0), 0);

  return { overallProgress, totalTimeSpent };
}

/**
 * Revoke a certificate
 */
export async function revokeCertificate(
  certificateId: string,
  reason: string,
  actorId: string
): Promise<boolean> {
  const results = await db
    .update(learningCertificates)
    .set({ status: 'revoked' })
    .where(eq(learningCertificates.id, certificateId))
    .returning();

  // Log revocation (would use audit logging module)
  return results.length > 0;
}

/**
 * Get all certificates for a user
 */
export async function getUserCertificates(userId: string): Promise<any[]> {
  return db
    .select({
      certificate: learningCertificates,
      path: learningPaths,
    })
    .from(learningCertificates)
    .innerJoin(learningPaths, eq(learningCertificates.pathId, learningPaths.id))
    .where(eq(learningCertificates.userId, userId))
    .orderBy(desc(learningCertificates.issuedAt));
}

/**
 * Get a certificate by number
 */
export async function getCertificateByNumber(certificateNumber: string): Promise<any | null> {
  const results = await db
    .select({
      certificate: learningCertificates,
      path: learningPaths,
    })
    .from(learningCertificates)
    .innerJoin(learningPaths, eq(learningCertificates.pathId, learningPaths.id))
    .where(eq(learningCertificates.certificateNumber, certificateNumber))
    .limit(1);

  return results[0] || null;
}

/**
 * Get certificate statistics
 */
export async function getCertificateStatistics(pathId?: string): Promise<{
  totalIssued: number;
  totalRevoked: number;
  byPath: Record<string, number>;
}> {
  const conditions = pathId ? eq(learningCertificates.pathId, pathId) : undefined;

  const allCertificates = await db
    .select()
    .from(learningCertificates)
    .where(conditions);

  const totalIssued = allCertificates.filter(c => c.status === 'issued').length;
  const totalRevoked = allCertificates.filter(c => c.status === 'revoked').length;

  const byPath: Record<string, number> = {};
  allCertificates.forEach(c => {
    byPath[c.pathId] = (byPath[c.pathId] || 0) + 1;
  });

  return {
    totalIssued,
    totalRevoked,
    byPath,
  };
}
